apiVersion: v1
data:
  mapRoles: |
    - groups:
      -system:masters
      rolearn: arn:aws:iam::014802573595:role/UdacityFlaskDeployCBKubectlRole
      username: Admin
    - rolearn: arn:aws:iam::014802573595:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - groups:
      - eks-console-dashboard-restricted-access-group
      userarn: arn:aws:iam::014802573595:user/Admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::014802573595:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-10-12T17:37:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5235"
  uid: cfe83022-d01e-4f31-9e8c-9d8d8a1e9f2a
